bn:
  eps: 1.0e-05
  mom: 0.1
cfg_dest: config.yaml
custom_metrics: []
dataset:
  add_ports: true
  augment_feature: []
  augment_feature_dims: []
  augment_feature_repr: original
  augment_label: ''
  augment_label_dims: 0
  cache_load: false
  cache_save: false
  dir: ./Data
  edge_dim: 128
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: Hetero_Raw
  edge_encoder_num_types: 0
  edge_message_ratio: 0.8
  edge_negative_sampling_ratio: 1.0
  edge_train_mode: all
  encoder: true
  encoder_bn: true
  encoder_dim: 128
  encoder_name: db
  format: AML
  infer_link_label: None
  label_column: none
  label_table: none
  location: local
  name: Small-HI
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: Hetero_Raw
  node_encoder_num_types: 0
  rand_split: false
  remove_feature: false
  resample_disjoint: false
  resample_negative: false
  reverse_mp: false
  shuffle_split: true
  slic_compactness: 10
  split:
  - 0.8
  - 0.1
  - 0.1
  split_dir: ./splits
  split_index: 0
  split_mode: standard
  task: hetero_edge
  task_entity:
  - node
  - to
  - node
  task_type: classification
  to_undirected: false
  transductive: true
  transform: none
  tu_simple: true
device: auto
example_arg: example
example_group:
  example_arg: example
gnn:
  A_embed: true
  K: 10
  act: relu
  agg: add
  alpha: 0.1
  attn_dropout: 0.0
  attn_final_linear: false
  attn_final_linear_bn: false
  attn_heads: 1
  batch_norm: false
  batchnorm: false
  clear_feature: true
  dim_inner: 16
  dropout: 0.2
  edge_updates: false
  flow: source_to_target
  head: hetero_edge
  hops: 7
  input_dropout: 0.0
  jumping_knowledge: false
  keep_edge: 0.5
  l2norm: true
  layer_norm: false
  layer_type: generalconv
  layers_mp: 2
  layers_post_mp: 1
  layers_pre_mp: 0
  msg_direction: single
  normalize_adj: false
  output_l2_norm: false
  residual: true
  self_msg: concat
  skip_every: 1
  stage_type: stack
  use_linear: false
gpu_mem: false
gt:
  act: gelu
  attn_dropout: 0.3
  attn_heads: 8
  attn_mask: Edge
  batch_norm: false
  dim_hidden: 64
  dropout: 0.2
  edge_weight: true
  ffn: Type
  full_graph: true
  gamma: 1.0e-05
  head: hetero_edge
  hops: 2
  input_dropout: 0.0
  jumping_knowledge: false
  l2_norm: false
  layer_norm: true
  layer_type: SparseNodeTransformer
  layers: 2
  layers_post_gt: 2
  layers_pre_gt: 0
  pna_degrees: []
  residual: Fixed
  virtual_nodes: 0
mem:
  inplace: false
metric_agg: argmax
metric_best: f1
model:
  edge_decoding: dot
  graph_pooling: mean
  loss_fun: weighted_cross_entropy
  loss_fun_weight:
  - 1
  - 6
  match_upper: true
  size_average: mean
  thresh: 0.5
  type: GTModel
name_tag: ''
num_threads: 8
num_workers: 8
optim:
  base_lr: 0.001
  batch_accumulation: 8
  clip_grad_norm: true
  clip_grad_norm_value: 1.0
  lr_decay: 0.1
  max_epoch: 500
  min_lr: 0.0
  momentum: 0.9
  num_warmup_epochs: 5
  optimizer: adamW
  reduce_factor: 0.1
  schedule_patience: 10
  scheduler: cosine_with_warmup
  steps:
  - 30
  - 60
  - 90
  weight_decay: 1.0e-05
out_dir: .results/AML-Small-HI-SparseNodeGT_tester
posenc_ElstaticSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: range(10)
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_EquivStableLapPE:
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  raw_norm_type: none
posenc_HKdiagSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_ComplEx:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_DistMult:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_GNN:
  act: relu
  agg: mean
  attn_dropout: 0.0
  batch_norm: false
  dim_pe: 16
  dropout: 0.0
  enable: false
  input_dropout: 0.0
  layer_norm: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  pre_layers: 0
  raw_norm_type: none
posenc_Hetero_Label:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_Metapath:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_Node2Vec:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_RWSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_SDAB:
  dim_pe: 0
  enable: false
  enable_path: false
  node_degrees_only: false
  num_spatial_types: 0
posenc_Hetero_SDPE:
  dim_pe: 0
  enable: false
  num_spatial_types: 0
posenc_Hetero_TransE:
  dim_pe: 16
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_Hetero_kHopAB:
  dim_pe: 0
  enable: false
  num_spatial_types: 0
posenc_Hetero_kHopAug:
  dim_pe: 0
  enable: false
  num_spatial_types: 0
posenc_Homo_GNN:
  act: relu
  agg: mean
  attn_dropout: 0.0
  batch_norm: false
  dim_pe: 16
  dropout: 0.0
  enable: false
  input_dropout: 0.0
  layer_norm: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  pre_layers: 0
  raw_norm_type: none
posenc_LapPE:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_RWSE:
  dim_pe: 16
  enable: false
  kernel:
    times: []
    times_func: ''
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  post_layers: 0
  raw_norm_type: none
posenc_SignNet:
  dim_pe: 16
  eigen:
    eigvec_norm: L2
    laplacian_norm: sym
    max_freqs: 10
  enable: false
  layers: 3
  model: none
  n_heads: 4
  pass_as_var: false
  phi_hidden_dim: 64
  phi_out_dim: 4
  post_layers: 0
  raw_norm_type: none
pretrained:
  dir: ''
  freeze_main: false
  reset_prediction_head: true
print: both
round: 5
run_dir: .results
run_multiple_splits: []
seed: 41
share:
  dim_in: 1
  dim_out: 1
  num_splits: 1
tensorboard_agg: true
tensorboard_each_run: false
train:
  add_ego_id: true
  auto_resume: false
  batch_size: 2048
  ckpt_best: false
  ckpt_clean: true
  ckpt_period: 100
  enable_ckpt: true
  epoch_resume: -1
  eval_period: 4
  iter_per_epoch: 256
  mode: custom
  neighbor_sizes:
  - 50
  - 50
  neighbor_sizes_dict: ''
  node_per_graph: 32
  num_parts: 10
  persistent_workers: true
  pin_memory: true
  radius: extend
  sample_node: false
  sampler: link_neighbor
  skip_train_eval: false
  tqdm: true
  walk_length: 4
val:
  iter_per_epoch: 256
  node_per_graph: 32
  radius: extend
  sample_node: false
  sampler: link_neighbor
  tqdm: true
view_emb: false
wandb:
  entity: junhonghust
  name: ''
  project: unifiedGT
  use: false
