#!/bin/bash

#SBATCH --job-name=run_bank_analysis
#SBATCH --output=bankanalysis.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=4        # Schedule 8 cores (includes hyperthreading)
#SBATCH --mem=32G
#SBATCH --time=8:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=cores       # Run on GPU queue
#SBATCH --mail-type=END,FAIL

echo "Running on $(hostname):"
module load Anaconda3
source activate fraudGT

python bank_analysis.py
