out_dir: .results
metric_best: f1
seed: 42
wandb: {use: false, project: unifiedGT}
dataset: {dir: AML_something_bank_001, format: AML, name: Small-HI, add_ports: true,
  task: hetero_edge, task_type: classification, task_entity: '(''node'', ''to'', ''node'')',
  transductive: true, node_encoder: true, node_encoder_name: Hetero_Raw, node_encoder_bn: false,
  edge_encoder: true, edge_encoder_name: Hetero_Raw, edge_encoder_bn: false}
num_threads: 8
num_workers: 8
train:
  mode: custom
  sampler: link_neighbor
  neighbor_sizes: [50, 50]
  add_ego_id: true
  iter_per_epoch: 256
  batch_size: 2048
  eval_period: 4
  ckpt_period: 100
  tqdm: true
  persistent_workers: true
  pin_memory: true
val: {sampler: link_neighbor, iter_per_epoch: 256, tqdm: true}
model:
  type: GTModel
  loss_fun: weighted_cross_entropy
  loss_fun_weight: [1, 6]
  edge_decoding: dot
  graph_pooling: mean
gt: {layer_type: SparseNodeTransformer, layers_pre_gt: 0, layers: 2, layers_post_gt: 2,
  attn_heads: 8, dim_hidden: 64, input_dropout: 0.0, dropout: 0.2, attn_dropout: 0.3,
  batch_norm: false, layer_norm: true, l2_norm: false, act: gelu, attn_mask: Edge,
  residual: Fixed, ffn: Type, jumping_knowledge: false}
gnn: {dropout: 0.2}
optim: {batch_accumulation: 8, clip_grad_norm: true, optimizer: adamW, weight_decay: 1e-5,
  base_lr: 0.001, max_epoch: 500, scheduler: cosine_with_warmup, num_warmup_epochs: 5}
